"""Tests for DNA file parser."""
import pytest
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
from parser import parse_dna_file, parse_23andme, parse_ancestrydna


SAMPLE_23ANDME = b"""# This data file generated by 23andMe
# rsid\tchromosome\tposition\tgenotype
rs429358\t19\t45411941\tTC
rs7412\t19\t45412079\tCC
rs6025\t1\t169519049\tCC
rs7903146\t10\t114758349\tCT
rs5219\t11\t17388025\tTT
rs1333049\t9\t22122503\tCG
rs4244285\t10\t96521657\tGA
rs4149056\t12\t21178615\tTC
"""

SAMPLE_ANCESTRYDNA = b"""#AncestryDNA raw data download
rsid\tchromosome\tposition\tallele1\tallele2
rs429358\t19\t45411941\tT\tC
rs7412\t19\t45412079\tC\tC
rs6025\t1\t169519049\tC\tC
rs7903146\t10\t114758349\tC\tT
"""

JUNK_FILE = b"this is not a dna file at all lol"

SHORT_FILE = b"# header\nrs123\t1\t100\tAA"


def test_parse_23andme_snps():
    lines = SAMPLE_23ANDME.decode().splitlines()
    snps = parse_23andme(lines)
    assert "rs429358" in snps
    assert snps["rs429358"] == "TC"
    assert "rs7412" in snps
    assert snps["rs7412"] == "CC"


def test_parse_ancestrydna_snps():
    lines = SAMPLE_ANCESTRYDNA.decode().splitlines()
    snps = parse_ancestrydna(lines)
    assert "rs429358" in snps
    assert snps["rs429358"] == "TC"


def test_parse_dna_file_23andme():
    # Build a large enough fake file
    header = b"# This data file generated by 23andMe\n# rsid\tchromosome\tposition\tgenotype\n"
    rows = b""
    for i in range(2000):
        rows += f"rs{100000 + i}\t1\t{i * 100}\tAA\n".encode()
    rows += SAMPLE_23ANDME[SAMPLE_23ANDME.find(b"rs429358"):]
    content = header + rows

    snps, fmt, count = parse_dna_file(content)
    assert fmt == "23andme"
    assert count >= 2000
    assert "rs429358" in snps


def test_parse_dna_file_rejects_junk():
    with pytest.raises(ValueError, match="too short|SNPs parsed"):
        parse_dna_file(JUNK_FILE)


def test_parse_dna_file_rejects_short():
    with pytest.raises(ValueError):
        parse_dna_file(SHORT_FILE)


def test_no_raw_snps_in_output():
    """Ensure parse returns structured dict, not file content."""
    header = b"# This data file generated by 23andMe\n# rsid\tchromosome\tposition\tgenotype\n"
    rows = b""
    for i in range(2000):
        rows += f"rs{200000 + i}\t1\t{i * 100}\tCG\n".encode()
    content = header + rows

    snps, fmt, count = parse_dna_file(content)
    assert isinstance(snps, dict)
    # Values should be genotypes (2 chars), not file lines
    for v in list(snps.values())[:10]:
        assert len(v) == 2
        assert all(c in "ACGT" for c in v)
